<a href="https://colab.research.google.com/github/thomasanna/python-entri/blob/main/Task7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

1. How to extract all odd numbers from arr?







In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = np.mod(arr,2) != 0 # np.mod => get the reminder of each element of in array
odd_numbers = np.extract(condition,arr)
print(odd_numbers)

[1 3 5 7 9]


2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[np.mod(arr,2) != 0 ] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3. Convert a 1D array to a 2D array with 2 rows

In [ ]:
import numpy as np
arr=np.arange(10) # create 1D array with values 0 to 9
arr2d = arr.reshape(2,-1) # convert 1D array to 2D with 2 rows,
# the -1 automatically determines number of columns based on total size
print(arr2d)
#Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

[[0 1 2 3 4]
 [5 6 7 8 9]]


4. Stack arrays a and b vertically

In [1]:
import numpy as np
a = np.arange(10).reshape(2,-1)
print(f"a => {a}")
b = np.repeat(1, 10).reshape(2,-1) # np.repeat => here 1 repeated 10 times [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
print(f"b => {b}")
stackedArray = np.vstack((a,b)) #np.vstack stacks arrays vertically, meaning it stacks them on top of each other.
#(a,b) is a tuple containing 2 arrays a and b
print(f"stackedArray : {stackedArray}" )
#Desired Output:()

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

a => [[0 1 2 3 4]
 [5 6 7 8 9]]
b => [[1 1 1 1 1]
 [1 1 1 1 1]]
stackedArray : [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


5. Stack the arrays a and b horizontally.

In [5]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stackedArray = np.hstack((a,b))
print(stackedArray)

#Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


6. How to get the common items between two python numpy arrays?
   Get the common items between a and b

In [7]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b) #This function returns the sorted unique common elements that are present in both arrays
print(f"Common Items {common_items}")

Common Items [2 4]


7.How to remove from one array those items that exist in another?
  Q. From array a remove all items present in array b

In [8]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a,b) #returns the sorted unique values in array a that are not in array b
print(result)

[1 2 3 4]


8. How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match

In [11]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
matches = np.where(a==b)  #To get the positions where elements of arrays a and b match, you can use the np.where() function in NumPy
print(matches)

#Desired Output:

#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)


9. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a

In [13]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a>=5) & (a<=10)] # Boolean indexing to get items between 5 and 10
print(f"items between 5 and 10 : {result}")

#Desired Output:

#(array([6, 9, 10]),)

items between 5 and 10 : [ 6  9 10]
