<a href="https://colab.research.google.com/github/thomasanna/python-entri/blob/main/Task7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

1. How to extract all odd numbers from arr?







In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = np.mod(arr,2) != 0 # np.mod => get the reminder of each element of in array
odd_numbers = np.extract(condition,arr)
print(odd_numbers)

[1 3 5 7 9]


2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[np.mod(arr,2) != 0 ] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3. Convert a 1D array to a 2D array with 2 rows

In [ ]:
import numpy as np
arr=np.arange(10) # create 1D array with values 0 to 9
arr2d = arr.reshape(2,-1) # convert 1D array to 2D with 2 rows,
# the -1 automatically determines number of columns based on total size
print(arr2d)
#Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

[[0 1 2 3 4]
 [5 6 7 8 9]]


4. Stack arrays a and b vertically

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
print(f"a => {a}")
b = np.repeat(1, 10).reshape(2,-1) # np.repeat => here 1 repeated 10 times [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
print(f"b => {b}")
stackedArray = np.vstack((a,b)) #np.vstack stacks arrays vertically, meaning it stacks them on top of each other.
#(a,b) is a tuple containing 2 arrays a and b
print(f"stackedArray : {stackedArray}" )
#Desired Output:()

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

a => [[0 1 2 3 4]
 [5 6 7 8 9]]
b => [[1 1 1 1 1]
 [1 1 1 1 1]]
stackedArray : [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
