<a href="https://colab.research.google.com/github/thomasanna/python-entri/blob/main/Task7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

1. How to extract all odd numbers from arr?







In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = np.mod(arr,2) != 0 # np.mod => get the reminder of each element of in array
odd_numbers = np.extract(condition,arr)
print(odd_numbers)

[1 3 5 7 9]


2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[np.mod(arr,2) != 0 ] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


3. Convert a 1D array to a 2D array with 2 rows

In [ ]:
import numpy as np
arr=np.arange(10) # create 1D array with values 0 to 9
arr2d = arr.reshape(2,-1) # convert 1D array to 2D with 2 rows,
# the -1 automatically determines number of columns based on total size
print(arr2d)
#Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

[[0 1 2 3 4]
 [5 6 7 8 9]]


4. Stack arrays a and b vertically

In [1]:
import numpy as np
a = np.arange(10).reshape(2,-1)
print(f"a => {a}")
b = np.repeat(1, 10).reshape(2,-1) # np.repeat => here 1 repeated 10 times [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
print(f"b => {b}")
stackedArray = np.vstack((a,b)) #np.vstack stacks arrays vertically, meaning it stacks them on top of each other.
#(a,b) is a tuple containing 2 arrays a and b
print(f"stackedArray : {stackedArray}" )
#Desired Output:()

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

a => [[0 1 2 3 4]
 [5 6 7 8 9]]
b => [[1 1 1 1 1]
 [1 1 1 1 1]]
stackedArray : [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


5. Stack the arrays a and b horizontally.

In [5]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
stackedArray = np.hstack((a,b))
print(stackedArray)

#Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


6. How to get the common items between two python numpy arrays?
   Get the common items between a and b

In [7]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b) #This function returns the sorted unique common elements that are present in both arrays
print(f"Common Items {common_items}")

Common Items [2 4]


7.How to remove from one array those items that exist in another?
  Q. From array a remove all items present in array b

In [8]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a,b) #returns the sorted unique values in array a that are not in array b
print(result)

[1 2 3 4]


8. How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match

In [11]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
matches = np.where(a==b)  #To get the positions where elements of arrays a and b match, you can use the np.where() function in NumPy
print(matches)

#Desired Output:

#> (array([1, 3, 5, 7]),)

(array([1, 3, 5, 7], dtype=int64),)


9. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a

In [13]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
result = a[(a>=5) & (a<=10)] # Boolean indexing to get items between 5 and 10
print(f"items between 5 and 10 : {result}")

#Desired Output:

#(array([6, 9, 10]),)

items between 5 and 10 : [ 6  9 10]


Pandas

Pandas Data Series

In [14]:
!pip install pandas

1. Write a Pandas program to convert a dictionary to a Pandas series.

In [16]:
import pandas as pd
dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
series = pd.Series(dict)  # Convert dictionary to Pandas Series
print(series)

a    100
b    200
c    300
d    400
e    800
dtype: int64


2. Write a Pandas program to convert a NumPy array to a Pandas series.

Sample Series:
NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

In [17]:
import pandas as pd
import numpy as np
arr = np.array([10,20,30,40,50])
series = pd.Series(arr)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int32


3. Write a Pandas program to change the data type of given a column or a Series.

Sample Series:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [20]:
import pandas as pd
series = pd.Series(['100','200','python','300.12','400'])
# Change the data type to numeric
converted_series = pd.to_numeric(series,errors='coerce')
print(converted_series)

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


4. Write a Pandas program to convert the first column of a DataFrame as a Series.
Sample Output:  
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>

In [23]:
import pandas as pd
data = {'col1':[1,2,3,4,7,11],
        'col2' : [4,5,6,9,5,0],
        'col3' : [7,5,8,12,1,11]}
df = pd.DataFrame(data)
print(df)
first_column = df['col1']
print('First column as a series')
print(first_column)

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
First column as a series
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


5. Write a Pandas program to convert a given Series to an array.
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>

In [25]:
import pandas as pd
series = pd.Series(['100','200','python','300.12','400'])
print("Original Data Series:")
print(series)
print("Series to an array")
arr = series.values
print(arr)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


6 Write a Pandas program to convert Series of lists to one Series.

Sample Output:
Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

In [31]:
import pandas as pd
series = pd.Series([['Red','Green','White'],['Red','Black'],['Yellow']])
print("Original Series of list")
print(series)
print("One Series")
one_series = series.explode().reset_index(drop = True) ## Convert Series of lists to one Series and reset index
print(one_series)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


##7.Write a Pandas program to sort a given Series.
```
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object
```

In [35]:
import pandas as pd
series = pd.Series(['100','200','python','300.12','400'])
print("original series")
print(series)
sorted_series = series.sort_values()
print("sorted series")
print(sorted_series)

original series
0       100
1       200
2    python
3    300.12
4       400
dtype: object
sorted series
0       100
1       200
3    300.12
4       400
2    python
dtype: object


##Pandas DataFrame

##1.Write a Pandas program to create a dataframe from a dictionary and display it.
```
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
Expected Output:
    X   Y   Z                                                         
0  78  84  86                                                        
1  85  94  97                                                         
2  96  89  96                                                      
3  80  83  72                                                         
4  86  86  83

```

In [37]:
import pandas as pd
data = {'x':[78,85,96,80,86],
        'y':[84,94,89,83,86],
        'z':[86,97,96,72,83]}
df = pd.DataFrame(data)
print(df)

    x   y   z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


##2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
....                              
i         2      Kevin      no    8.0                                
j         1      Jonas     yes   19.0

```

In [38]:
import pandas as pd
data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
        }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data,index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


##3. Write a Pandas program to get the first 3 rows of a given DataFrame.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
First three rows of the data frame:                                   
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
c         2  Katherine     yes   16.5

```

In [39]:
import pandas as pd
data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
        }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data,index=labels)
first_3_rows = df.iloc[:3] ## Get the first 3 rows of the DataFrame
print(first_3_rows)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


##4.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns:                                               
        name  score                                                  
a  Anastasia   12.5                                                   
b       Dima    9.0                                                
c  Katherine   16.5                                                    
...                                                  
h      Laura    NaN                                                   
i      Kevin    8.0                                                  
j      Jonas   19.0
```

In [43]:
import pandas as pd
data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
        }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data,index=labels)

result = df[['name','score']] ## Select 'name' and 'score' columns
print(result)


        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


##5.  Write a Pandas program to select the specified columns and rows from a given data frame.
```
Sample Python dictionary data and list labels:
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns and rows:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

```

In [47]:
import pandas as pd
data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
        }
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data,index=labels)
result = df.iloc[[1,3,5,6],[1,3]] ## Select specific columns and rows using row numbers

print(result)

   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes
